<a href="https://colab.research.google.com/github/Danylo5051/-/blob/main/%D0%A1%D0%B0%D1%82%D0%BA%D0%BE_1hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
vector_20 = np.arange(1, 21)
print("Вектор натуральних чисел:\n", vector_20)

Вектор натуральних чисел:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
ones_matrix = np.ones((4, 4))
print("\nМатриця 4x4 з одиниць:\n", ones_matrix)


Матриця 4x4 з одиниць:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
random_matrix_5x5 = np.random.uniform(-1, 1, (5, 5))
print("Матриця 5x5 (від -1 до 1):\n", random_matrix_5x5)

Матриця 5x5 (від -1 до 1):
 [[ 0.35020225  0.78202713  0.08342234 -0.27777461  0.18564258]
 [-0.98762195 -0.34709701 -0.3864991  -0.97859014 -0.36425718]
 [-0.66132996 -0.3711473  -0.24326871  0.32372559  0.1231443 ]
 [-0.62550909  0.30611118  0.69300664 -0.54268135  0.63333156]
 [ 0.39205652 -0.01644356  0.60806593 -0.03244918 -0.98184202]]


In [5]:
random_matrix_3x3 = np.random.rand(3, 3)
print("\nМатриця 3x3 (від 0 до 1):\n", random_matrix_3x3)


Матриця 3x3 (від 0 до 1):
 [[0.27930283 0.85544122 0.1732876 ]
 [0.42076878 0.604617   0.95927975]
 [0.8384525  0.46338847 0.5408674 ]]


In [6]:
arr1= np.random.randint(1, 21, 6)
arr2= np.random.randint(1, 21, 6)

print(f"Масив 1: {arr1}")
print(f"Масив 2: {arr2}")
print("Додавання:", arr1 + arr2)
print("Віднімання:", arr1 - arr2)
print("Множення:", arr1 * arr2)

Масив 1: [ 3  1 17  2  3  7]
Масив 2: [ 5 19  9 11  2 20]
Додавання: [ 8 20 26 13  5 27]
Віднімання: [ -2 -18   8  -9   1 -13]
Множення: [ 15  19 153  22   6 140]


In [7]:
mat_a = np.random.randint(1, 6, (3, 2))
mat_b = np.random.randint(1, 6, (2, 4))
result_dot = np.dot(mat_a, mat_b)

print("Матриця 3x2:\n", mat_a)
print("Матриця 2x4:\n", mat_b)
print("Результат множення (3x4):\n", result_dot)

Матриця 3x2:
 [[3 4]
 [2 4]
 [1 2]]
Матриця 2x4:
 [[1 2 1 3]
 [4 3 4 3]]
Результат множення (3x4):
 [[19 18 19 21]
 [18 16 18 18]
 [ 9  8  9  9]]


In [8]:
mat_to_transpose = np.random.rand(3, 3)
print("Оригінальна матриця:\n", mat_to_transpose)
print("Транспонована матриця:\n", mat_to_transpose.T)

Оригінальна матриця:
 [[4.06874119e-01 6.26526705e-01 6.95076594e-01]
 [5.89387493e-04 7.57278356e-01 3.48418686e-01]
 [3.89956562e-01 3.93672405e-01 8.88843064e-01]]
Транспонована матриця:
 [[4.06874119e-01 5.89387493e-04 3.89956562e-01]
 [6.26526705e-01 7.57278356e-01 3.93672405e-01]
 [6.95076594e-01 3.48418686e-01 8.88843064e-01]]


In [9]:
mat_c = np.random.randint(1, 11, (3, 3))
mat_d = np.random.randint(1, 11, (3, 3))
print("\nМатриця C:\n", mat_c)
print("Матриця D:\n", mat_d)
print("Різниця C - D:\n", mat_c - mat_d)


Матриця C:
 [[5 1 9]
 [3 9 4]
 [6 3 1]]
Матриця D:
 [[3 9 2]
 [2 4 8]
 [6 8 3]]
Різниця C - D:
 [[ 2 -8  7]
 [ 1  5 -4]
 [ 0 -5 -2]]


In [10]:
mat_e = np.random.randint(-5, 6, (3, 3))
mat_f = np.random.randint(-5, 6, (3, 3))
print("Матриця E:\n", mat_e)
print("Матриця F:\n", mat_f)
print("Матричний добуток E * F:\n", np.dot(mat_e, mat_f))

Матриця E:
 [[ 1  1 -2]
 [ 0 -2  5]
 [ 1 -2 -1]]
Матриця F:
 [[ 5  1 -3]
 [-2  5 -2]
 [-2  4  1]]
Матричний добуток E * F:
 [[  7  -2  -7]
 [ -6  10   9]
 [ 11 -13   0]]


In [11]:
mat_g = np.random.uniform(-1, 1, (3, 3))
row_sums = mat_g.sum(axis=1).reshape(-1, 1)

In [12]:
print("\nМатриця G:\n", mat_g)
print("Вектор-стовпчик сум рядків:\n", row_sums)


Матриця G:
 [[ 0.98032368  0.53118298 -0.95736955]
 [-0.10547076 -0.12729617  0.13844126]
 [ 0.90435963  0.15018482  0.7678207 ]]
Вектор-стовпчик сум рядків:
 [[ 0.5541371 ]
 [-0.09432566]
 [ 1.82236515]]
